#!/usr/bin/env python

import os
import sys
import torch
from controlnet_aux import OpenposeDetector
from diffusers import StableDiffusionPipeline, ControlNetModel

# append project directory to path so predict.py can be imported
sys.path.append('.')

from predict import MODEL_NAME, MODEL_CACHE, CONTROL_NAME, CONTROL_CACHE, OPENPOSE_NAME, POSE_CACHE

# Create cache folders
if not os.path.exists(MODEL_CACHE):
    os.makedirs(MODEL_CACHE)

if not os.path.exists(CONTROL_CACHE):
    os.makedirs(CONTROL_CACHE)

if not os.path.exists(POSE_CACHE):
    os.makedirs(POSE_CACHE)

# Download controlnet
openpose = OpenposeDetector.from_pretrained(
    CONTROL_NAME,
    cache_dir=CONTROL_CACHE,
)

controlnet = ControlNetModel.from_pretrained(
    OPENPOSE_NAME,
    torch_dtype=torch.float16
)
controlnet.save_pretrained(POSE_CACHE)

pipe = StableDiffusionPipeline.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    use_safetensors=True,
)
pipe.save_pretrained(MODEL_CACHE, safe_serialization=True)
